default: &default
  adapter: postgresql
  encoding: unicode
  user: <%= ENV["TRIPHERO_DB_USERNAME"] %>
  password: <%= ENV["TRIPHERO_DB_PASSWORD"] %>
  host: <%= ENV["TRIPHERO_DB_HOSTNAME"]  %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV["TRIPHERO_DB_PORT"] %>
  wait_timeout: 900 # 15 minutes.
  timeout: 5000 # 5 seconds.

development:
  <<: *default
  database: triphero_development

test:
  <<: *default
  database: triphero_test

production:
  <<: *default
  database: triphero
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>
